export const ADD_CHAT = "CHATS::ADD_CHAT";
export const DELETE_CHAT = "CHATS::DELETE_CHAT";
export const SEND_MESSAGE = "CHATS::SEND_MESSAGE";
export const COLOR_MESSAGE_LIST = "CHATS::COLOR_MESSAGE_LIST";
